language: java

jdk:
  - oraclejdk8

branches:
  only:
    - build

env:
  global:
  - secure: "njypzWiFG3IhRaX6ZXat3Fd3R68yH1gEj3H4V63gg8DxfipVlMZ8Krf1mU3TvVTnQh2
  p8J4Wd9y6z0zydolAqwnF8nskV/HKOF+l/c2hgxPpt4+7WzbgKf0NF7myWNCpfQe57m7CTKiyXXRfd
  Z9+PAzC1BTFN6pbwUvBeUjs/8+NeF3C6ub9qu8wdwiyqpnNIKhG3i0h7GO8SuxGHUgOb90RuwVweZf
  EeSpDmeKLhvJ47HL9UZDI/2T2ZTYFs9r2+f06WCk448c1xzx6QSddg9N5V4SzNgERgCtJ5Vg0nh/4B
  PBhitvPD7KMVwxFeE2aF2DZ4Z2wWJ0zEk9itdgFvdib0ET9nhsVuqB/KUJdaRlR9sFJrHLPxMY7ASF
  xMFqenqdrSpJ+oSmTp/gcJHf5CEkGsgoXV++LFPdODyr3NvacoTi7th4Wi/ObUUEGkdfWGeY5l0mNj
  f2xzOhaeMgQ7zx9m3FXsRtIMCYizBh27s4hk5IkWNyh1wWys3dkRnj9H+p01ssPFY1Y6u9gj81Pox0
  FyEACRJeWmp/yL/+4h+mD6MdF8FAs725FHjvPkA1G8oYmRxrglKvnZSdaCNkK+yLSdWXHu8tvTLjdN
  JY+Bf/q/Q+23kALen4LCtoJw/QLyjRtN5YbrAeEKxpzlogyCkPqU95Y8jz+DDfyTKGwX68="

install:
  - mvn install -B -V -e

after_success:
  - mvn javadoc:javadoc
  - chmod +x travis/push-javadoc-to-gh-pages.sh
  - travis/push-javadoc-to-gh-pages.sh